### ISSUE TITLE
Macintosh ABI non-zero vtable offsets

### ISSUE THREAD

**Issue by snailspeed3** [DotKuribo/llvm-project#5]
- [x] Add a `VPtrOffset` to `RecordLayout`, specifically for CodeWarrior (reference the Microsoft-specific `VBPtrOffset` field)
  - [x] Add a `getVPtrOffset()` getter as well, referencing `getVBPtrOffset()`
- [x] Add a `VPtrOffset` to `ItaniumRecordLayoutBuilder`
- [x] At the RecordLayoutBuilder:1061 area, set `VPtrOffset` to `DataSize` before you increase the buffer to account for the vtable pointer (in the CodeWarrior case)
- [x] Extend the `RecordLayout` C++ constructor to take in `vptroffset`, and have the non-CodeWarrior calls specify `CharUnits::fromQuantity(-1)` for it. (calls are in RecordLayoutBuilder.cpp:3248 or so) 
- [x] Add this edge case to VTableBuilder.cpp:1710
 - TODO: Make sure to account for AddressPointLocation being in units of sizeof(void*), not bytes.
   - ex `CharUnits PtrWidth = Context.toCharUnitsFromBits(Context.getTargetInfo().getPointerWidth(0));`
```cpp
if (/* abi check */ && !VTableIndices.empty()) {
  // FIXME: No idea if this is valid or not. Under what cases can a class have multiple vtables not from a base?
  assert(VTableIndices.size() == 1 && "Cannot have multiple vtables in the same sub-object");
  AddressPoints.insert(
      std::make_pair(BaseSubobject(RD, OffsetInLayoutClass),
                     VTableLayout::AddressPointLocation{
                         RD->getVPtrOffset(),
                         unsigned(AddressPoint - VTableIndex)}));
} else { ... }
```

**Comment by JoshuaMKW** [comment]
All tasks have been implemented, whether they work correctly or not is untested currently.

**Comment by snailspeed3** [comment]
Looks like this task still needs to be done:
>  At the RecordLayoutBuilder:1061 area, set VPtrOffset to DataSize before you increase the buffer to account for the vtable pointer (in the CodeWarrior case)

**Comment by JoshuaMKW** [comment]
VPtrOffset is now being properly set, although codegen seems to be unaltered? I'm continuing investigation, it intrigues me that changes being made aren't having any affect on the output.

**Comment by JoshuaMKW** [comment]
Late to this, but all issues presented were fixed months back so I'm closing this issue now.
