### ISSUE TITLE
Virtual function calls behave poorly with high optimization

### ISSUE THREAD

**Issue by JoshuaMKW** [DotKuribo/llvm-project#7]
They seemingly optimize as a non virtual function would, being inlined and optimized away. This only happens on higher optimization settings.

The expected behavior is for these virtual function calls to remain intact as the compiler can't know if optimizing it would change runtime behavior.

**Comment by snailspeed3** [comment]
This isn't a bug. If the compiler can prove a virtual call at compile-time, it should be able to fold it away.
Consider C++20's constexpr virtual functions: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1064r0.html

**Comment by JoshuaMKW** [comment]
Ah, that's new to me, thanks for the info! Turns out this was caused by improper variable usage in VTableBuilder.cpp

**Comment by snailspeed3** [comment]
Ah, so the issue was that the wrong VTable was being called in multi-inheritance cases, which the optimizer validly optimized (garbage in, garbage out)?

Can you add a test to ensure this doesn't happen again?

**Comment by JoshuaMKW** [comment]
Sure, I'll get to making it and have it pushed when it's ready.
